name: Deploy to Vercel

on:
  push:
    branches:
      - main
    # Evitamos que este workflow se dispare si solo cambias el Excel, 
    # queremos que espere a que el robot genere los JSON.
    paths-ignore:
      - 'my-ipi-dashboard/data/raw/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/my-ipi-dashboard/package-lock.json'

      - name: Install dependencies
        working-directory: my-ipi-dashboard
        run: npm ci

      - name: Build Next.js app
        working-directory: my-ipi-dashboard
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: my-ipi-dashboard
          vercel-args: '--prod'
          
